
services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    container_name: n8n
    environment:
      N8N_HOST: localhost
      N8N_PORT: 5678
      N8N_PROTOCOL: http
      NODE_ENV: development
      WEBHOOK_URL: http://localhost:5678/
      GENERIC_TIMEZONE: Europe/Istanbul
    volumes:
      - n8n_data:/home/node/.n8n
      - ./local-files:/files
    networks:
      - keycloak_network

volumes:
  n8n_data:

networks:
  keycloak_network:
    driver: bridge
    external: true

